name: Update Timeline Image

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      # Step 4: Run the Python script to generate the image
      - name: Generate Timeline Image
        run: python timeline.py

      # Step 5: Commit and Push the updated image
      - name: Commit and Push Timeline
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          git reset --soft origin/gh-pages
          git add --force timeline.png
          git commit -m "Update timeline image [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force
       
